# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Add support to default build

name: Continuous Integration with Gradle

permissions:
  contents: write # to upload release assets
  packages: write # to publish packages

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - bugfix/**
      - feature/**
      - hotfix/**
      - test/**
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

jobs:

  build-ci:
    name: Build ADempiere Mobile Service
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Setup Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 17
          architecture: x64

      - name: Setup Gradle 9
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 9.0.0 # current

      - name: Build with Gradle
        run: gradle build --warning-mode all --stacktrace
        env:
          ORG_GRADLE_PROJECT_deployUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_deployToken: ${{ secrets.DEPLOY_TOKEN }}
          ORG_GRADLE_PROJECT_deployRepository: ${{ secrets.DEPLOY_REPOSITORY }}
          GITHUB_DEPLOY_USER: ${{ github.actor }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOY_REPOSITORY: ${{ secrets.DEPLOY_REPOSITORY }}

      - name: Upload descriptor file artifact
        uses: actions/upload-artifact@v5
        with:
          name: adempiere-mobile-service.dsc
          path: build/descriptors/adempiere-mobile-service.dsc
          retention-days: 1
